-- PC Price Tracker - setup completo e idempotente
-- Pode ser executado mais de uma vez no SQL Editor do Supabase.

CREATE TABLE IF NOT EXISTS pecas (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tipo TEXT NOT NULL,
    nome TEXT NOT NULL,
    loja TEXT NOT NULL,
    link TEXT NOT NULL,
    preco NUMERIC(12,2) NOT NULL,
    atualizado_em TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE pecas ADD COLUMN IF NOT EXISTS fabricante TEXT;
ALTER TABLE pecas ADD COLUMN IF NOT EXISTS modelo TEXT;
ALTER TABLE pecas ADD COLUMN IF NOT EXISTS mpn TEXT;
ALTER TABLE pecas ADD COLUMN IF NOT EXISTS gtin TEXT;
ALTER TABLE pecas ADD COLUMN IF NOT EXISTS socket TEXT;
ALTER TABLE pecas ADD COLUMN IF NOT EXISTS memoria_tipo TEXT;
ALTER TABLE pecas ADD COLUMN IF NOT EXISTS formato TEXT;
ALTER TABLE pecas ADD COLUMN IF NOT EXISTS potencia_w NUMERIC(10,2);
ALTER TABLE pecas ADD COLUMN IF NOT EXISTS comprimento_mm NUMERIC(10,2);
ALTER TABLE pecas ADD COLUMN IF NOT EXISTS gpu_max_mm NUMERIC(10,2);
ALTER TABLE pecas ADD COLUMN IF NOT EXISTS psu_recomendada_w NUMERIC(10,2);
ALTER TABLE pecas ADD COLUMN IF NOT EXISTS formatos_suportados TEXT;
ALTER TABLE pecas ADD COLUMN IF NOT EXISTS observacoes TEXT;

CREATE TABLE IF NOT EXISTS historico (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    peca_id BIGINT NOT NULL REFERENCES pecas(id) ON DELETE CASCADE,
    preco NUMERIC(12,2) NOT NULL,
    data TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS montagens (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    faixa TEXT NOT NULL DEFAULT 'Personalizado',
    descricao TEXT,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE montagens ADD COLUMN IF NOT EXISTS orcamento NUMERIC(12,2);

CREATE TABLE IF NOT EXISTS montagem_pecas (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    montagem_id BIGINT NOT NULL REFERENCES montagens(id) ON DELETE CASCADE,
    peca_id BIGINT NOT NULL REFERENCES pecas(id) ON DELETE CASCADE,
    quantidade INTEGER NOT NULL DEFAULT 1 CHECK (quantidade > 0),
    UNIQUE (montagem_id, peca_id)
);

ALTER TABLE montagem_pecas ADD COLUMN IF NOT EXISTS travada BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS ofertas (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    peca_id BIGINT NOT NULL REFERENCES pecas(id) ON DELETE CASCADE,
    loja TEXT NOT NULL,
    link TEXT NOT NULL,
    preco NUMERIC(12,2) NOT NULL,
    frete NUMERIC(12,2) NOT NULL DEFAULT 0,
    preco_final NUMERIC(12,2) NOT NULL,
    disponivel BOOLEAN NOT NULL DEFAULT TRUE,
    origem TEXT NOT NULL DEFAULT 'manual',
    vendedor TEXT,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (peca_id, link)
);

ALTER TABLE ofertas ADD COLUMN IF NOT EXISTS produto_nome TEXT;
ALTER TABLE ofertas ADD COLUMN IF NOT EXISTS identificador_externo TEXT;
ALTER TABLE ofertas ADD COLUMN IF NOT EXISTS correspondencia NUMERIC(5,3);
ALTER TABLE ofertas ADD COLUMN IF NOT EXISTS moeda TEXT NOT NULL DEFAULT 'BRL';

CREATE TABLE IF NOT EXISTS historico_ofertas (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    oferta_id BIGINT NOT NULL REFERENCES ofertas(id) ON DELETE CASCADE,
    preco NUMERIC(12,2) NOT NULL,
    frete NUMERIC(12,2) NOT NULL DEFAULT 0,
    preco_final NUMERIC(12,2) NOT NULL,
    data TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS alertas (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    peca_id BIGINT NOT NULL REFERENCES pecas(id) ON DELETE CASCADE,
    preco_alvo NUMERIC(12,2) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_historico_peca ON historico(peca_id);
CREATE INDEX IF NOT EXISTS idx_montagem_pecas_montagem ON montagem_pecas(montagem_id);
CREATE INDEX IF NOT EXISTS idx_ofertas_peca ON ofertas(peca_id);
CREATE INDEX IF NOT EXISTS idx_ofertas_preco_final ON ofertas(peca_id, preco_final);
CREATE INDEX IF NOT EXISTS idx_historico_ofertas_oferta ON historico_ofertas(oferta_id);
CREATE INDEX IF NOT EXISTS idx_alertas_peca ON alertas(peca_id);

ALTER TABLE pecas ENABLE ROW LEVEL SECURITY;
ALTER TABLE historico ENABLE ROW LEVEL SECURITY;
ALTER TABLE montagens ENABLE ROW LEVEL SECURITY;
ALTER TABLE montagem_pecas ENABLE ROW LEVEL SECURITY;
ALTER TABLE ofertas ENABLE ROW LEVEL SECURITY;
ALTER TABLE historico_ofertas ENABLE ROW LEVEL SECURITY;
ALTER TABLE alertas ENABLE ROW LEVEL SECURITY;
